### ISSUE TITLE
About the evaluation on attribute preservation rate and identity preservation score 

### ISSUE THREAD

**Issue by lcd21** [InterDigitalInc/latent-transformer#3]
Thank you for making the code of this impressive work. Attribute preservation rate and identity preservation score are important metrics to show the disentanglement in Fig4 and Fig7. So could you please share source code for the evaluation on Attribute preservation rate and identity preservation score ? That's really helpful, thank you!

**Comment by Xu-Yao** [comment]
Hi, sorry to reply you late.

For the face attributes, we use this repo (https://github.com/TencentYoutuResearch/FaceAttribute-FAN)  to generate the results. Their model is also trained on CelebA to predict the 40 labels. We slightly modify their code to generate the results.

For the identity, we use a pretrained vgg face model. You can find the evaluation code here [id_evaluation.zip](https://github.com/InterDigitalInc/latent-transformer/files/7315988/id_evaluation.zip). For legal reason, we cannot provide the vggface model. You can download the original one from https://www.robots.ox.ac.uk/~vgg/software/vgg_face/.
