### ISSUE TITLE
inputs is not defined

### ISSUE THREAD

**Issue by ucalyptus2** [InterDigitalInc/latent-transformer#4]
for the inference.py modification suggested, inputs variable is not defined, rather input_cuda var is defined but that is not valid for entry into net(...) 

Please look into it and maybe some change in the instruction could be read.

cc: @Xu-Yao

**Comment by Xu-Yao** [comment]
Hi, I guess you are mentioning the encoding part using the PSP encoder. The modification that we proposed is just to save the latent codes generated by psp, to facilitate the video manipulation process. The two variables are already defined in the original inference.py file.
