### ISSUE TITLE
Using StyleGAN.get_latent instead of pipxel2style2pixel encoder

### ISSUE THREAD

**Issue by zhongtao93** [InterDigitalInc/latent-transformer#5]
Hi, it's ineffective when I use StyleGAN.get_latent instead of using pipxel2style2pixel encoder. 

`w_0 = trainer.StyleGAN.get_latent(torch.randn(1, 512, device=device)).repeat(1, 18, 1)`

The first column is generate image using w_o as above, the remaining four is teaser_attrs as the same of source code in figure_sequential_edit.ipynb
![image](https://user-images.githubusercontent.com/15263824/143996947-60c512d7-a747-447b-bdbb-d55dda6f8e37.png)

**Comment by Xu-Yao** [comment]
Hi, the pSp encoder maps a real image to an extended latent space W+, where each latent is different for the 18 layers. In the original latent space of StyleGAN, the 18 layers use the same latent w, as you did in this example. Our pretrained model is trained in the latent space W+ obtained with pSp encoder, such that the behavior will not be the same as in the original latent space. Maybe you can try to increase the scaling factor to see more editing effects. If you want to perform editing on synthetic images, you need to train the latent transformer in the original latent space.
